### ISSUE TITLE
Seems the driver stopped working on kernel 5.19.x

### ISSUE THREAD

**Issue by timonoj** [quo/ithc-linux#13]
Hi Quo,

Just wanted to give you a heads up, seems the ithc driver, while installed in my KDE Neon 5.25 (Ubuntu 20.04, Kernel 5.19.2), it no longer detects a touch input. It worked well during the 5.18.x kernels (although these ones gave me trouble with virtualbox, but that's unrelated), and also pefectly with 5.17.x, but since the upgrade to 5.19.x, there's now trouble...could you take a look to it?

Thanks so much!

**Comment by timonoj** [comment]
Yes, and in fact I got that error, about key being rejected. Let me check, thanks!

**Comment by qzed** [comment]
@timonoj As far as I can tell it's an issue with module signature verification. Disabling secureboot should be one workaround.

**Comment by lxdb** [comment]
https://gist.github.com/sbueringer/bd8cec239c44d66967cf307d808f10c4
That guide worked painless for me on Fedora 37 with kernel 5.19

**Comment by StollD** [comment]
DKMS on Fedora will actually generate its own keys in `/var/lib/dkms/` and automatically sign modules with them as of recently. The signature verification issue seems to be either Ubuntu specific or Linux 5.19 specific, so it does not affect Fedora (yet).

**Comment by qzed** [comment]
The latest kernel release (v5.19.4) should fix this.

**Comment by timonoj** [comment]
I can confirm kernel 5.19.4 fixed the issues both with ithc-linux and with vboxsvc! Thanks!

**Comment by Faexa** [comment]
For debian users : https://github.com/linux-surface/linux-surface/issues/906#issuecomment-1232826970
