### ISSUE TITLE
device not available `ithc_probe: hid_add_device failed with -110`

### ISSUE THREAD

**Issue by dbeal-eth** [quo/ithc-linux#16]
I installed ithc from git commit 02bf0eb using the dkms instructions. However, I have no touchscreen device listed under my libinput list, and `ithc` module is printing out some suspicious errors (`sudo dmesg | grep -i ithc`):

```
[  767.498937] ithc 0000:00:10.6: config: e0000002 00000000 001fc0ff 00000010 00000014 43495424 0de37ae8 0c1b045e 00000001 34fb1951 22fabca3 00000000 f48e9377 00040302 969ee474 53119add
[  767.499665] ithc 0000:00:10.6: registered device ithc
[  768.521677] ithc 0000:00:10.6: ithc_probe: hid_add_device failed with -110
[  768.521693] ithc: probe of 0000:00:10.6 failed with error -110
```

I have tried re-initializing the module after startup with `modprobe -r ithc && modprobe ithc`. After doing this, it prints the same output/error.

`uname -a`:

```
Linux daniel-surface 6.0.1-arch2-1-surface #1 SMP PREEMPT_DYNAMIC Fri, 14 Oct 2022 15:47:45 +0000 x86_64 GNU/Linux
```

Hardware: Microsoft Surface Laptop Studio, i7 16GB

Operating System: Arch Linux (rolling)

**Comment by dbeal-eth** [comment]
further expansion of grep command above reveals additional error output:

```
[  767.498937] ithc 0000:00:10.6: config: e0000002 00000000 001fc0ff 00000010 00000014 43495424 0de37ae8 0c1b045e 00000001 34fb1951 22fabca3 00000000 f48e9377 00040302 969ee474 53119add
[  767.499665] ithc 0000:00:10.6: registered device ithc
[  767.500857] DMAR: DRHD: handling fault status reg 2
[  767.500867] DMAR: [INTR-REMAP] Request device [01:05.0] fault index 0x40 [fault reason 0x26] Blocked an interrupt request due to source-id verification failure
[  768.521677] ithc 0000:00:10.6: ithc_probe: hid_add_device failed with -110
[  768.521693] ithc: probe of 0000:00:10.6 failed with error -110
```

**Comment by StollD** [comment]
Have you followed the steps in the README (under Notes)?

> If you get an error in dmesg saying "Blocked an interrupt request due to source-id verification failure", you will need to add the kernel parameter `intremap=nosid` and reboot. If you're using GRUB, you can do this with `sudo make set-nosid`. Alternatively, use the driver in polling mode by setting the `poll` module parameter (e.g. by running `echo options ithc poll | sudo tee /etc/modprobe.d/ithc-poll.conf` and reloading the module or rebooting).

**Comment by dbeal-eth** [comment]
didnt notice the note in the README. searched the entire internet, and the other issues on this repo. if you are filtering for `ithc` in dmesg, it may be better to identify the message by `ithc_probe: hid_add_device failed`

thanks for help!
