### ISSUE TITLE
Question about installation on SP8

### ISSUE THREAD

**Issue by WorldTeacher** [quo/ithc-linux#17]
So I recently got a SP8 and installed arch with the linux-surface on it.

I now want to try to enable the touchscreen and pen, but before I potentially break anything, I wanted to ask if the process I'll be doing is correct.

I'd do the following:

1.  clone [quo](https://github.com/quo) / [ithc-linux](https://github.com/quo/ithc-linux) and the latest build from https://github.com/linux-surface/iptsd/actions
2. install ithc-linux using the non dkms way
3. follow the installation provided in the iptsd readme.md

and hope that does everything

Is this all I have to do, or have I missed something? 

It's my first time compiling and installing, so I want to make sure I don't make any mistakes that might cost me time.

**Comment by quo** [comment]
I recommend the DKMS installation since it's more likely to set things up correctly for Secure Boot. But it depends on your distro.

Also, you'll need to add the `intremap=nosid` kernel parameter (or enable poll mode) as described in the ithc readme. On Debian, Ubuntu and other Debian-derived distros you can do this with `sudo make set-nosid`. For other distros, someone else will have to chime in.

**Comment by WorldTeacher** [comment]
> I recommend the DKMS installation since it's more likely to set things up correctly for Secure Boot. 

Does this matter if I didn't do the Secure Boot step in the instructions? When I first installed a SP5 I didn't do this step and it worked fine, so I did the same here.

Thanks for mentioning the `intremap=nosid`, I would have probably missed it.

**Comment by NP-chaonay** [comment]
> Does this matter if I didn't do the Secure Boot step in the instructions? When I first installed a SP5 I didn't do this step and it worked fine, so I did the same here.

1) SB  is not required
2) DKMS is way more recommended for who using SB since DKMS sysmte willl manage  the SB for you after the first setup
3) even you have not using SB, I still recommended to using DKMS, this system is the automate system to install driver to new kernel update, without this, you have to manage that thing by yourself (manging thing yourself's diffcult is depends on building complexisty and personal skill)

@WorldTeacher

**Comment by WorldTeacher** [comment]
Sorry for the late response, I was a bit busy. 

I tried installing and it seems like ithc-linux worked fine, but when I try to do `sudo ./etc/iptsd-find-hidraw` I get `/dev/` as a result.

What I did was:
```
$ git clone https://github.com/linux-surface/iptsd
$ cd iptsd
$ meson build
$ ninja -C build
```

any ideas?

**Comment by StollD** [comment]
Can you post your dmesg? Are you sure that ithc was successfully loaded? (singletouch needs to work)

**Comment by WorldTeacher** [comment]
In that case, it wasn't successfully loaded, as touch isn't working at all.

Then dmsg output is:
`dmesg: read kernel buffer failed: Operation not permitted
`

**Comment by StollD** [comment]
`sudo dmesg`

And yeah, if the module isnt loaded, `iptsd-find-hidraw` wont find anything.

**Comment by WorldTeacher** [comment]
this is the output of  `sudo dmesg`:
https://pastebin.com/jqA2z9ge

**Comment by StollD** [comment]
You didnt add `intremap=nosid` to your kernel commandline

**Comment by WorldTeacher** [comment]
i did the command `sudo make set-nosid`, but I guess it didn't work, will add it right now

**Comment by StollD** [comment]
That command runs `sudo update-grub` which only works on Debian based distros. Users of Arch and Fedora need to rebuild the grub configuration themselves.

**Comment by WorldTeacher** [comment]
did just that, single-touch works now

**Comment by WorldTeacher** [comment]
I just did the `sudo ninja -C build install` and multitouch and pen work now.

Thanks for the help ^^

**Comment by WorldTeacher** [comment]
only small thing I've noticed it that when the pen is used and the hand is resting on the screen, that it tries to create input from hand to pen. Example would be using pen in Krita and getting lines from hand to pen.

if needed, I can post an image tomorrow.

**Comment by NP-chaonay** [comment]
> only small thing I've noticed it that when the pen is used and the hand is resting on the screen, that it tries to create input from hand to pen. Example would be using pen in Krita and getting lines from hand to pen.
> 
> if needed, I can post an image tomorrow.

Does the touch only, make the line?

**Comment by WorldTeacher** [comment]
sorry for the late reply, I didn't see the notification...


I'm not quite sure what you mean by "does the touch only, make the line", so I took this image, maybe that explains it:
![Screenshot_20221109_165334](https://user-images.githubusercontent.com/41587052/200878034-adbf6126-9cce-488c-b0cb-661acad85440.png)

In this screenshot, Krita's touch screen draw was enabled.
Grey is pen and Hand on screen (you can see the 2 almost parrallel lines in the midle, where the pen was at, the other grey lines point to my hand)
Green is drawn by Hand
Red is drawn by pen with the hand in the air.

I also noticed that in xournal++ (again with the hand on screen), sometimes the pen doesn*t register and creates some dots in the text). 
![Screenshot_20221109_170228](https://user-images.githubusercontent.com/41587052/200879757-0c3cfa95-84fd-466f-96ee-d07a0ab7dc1b.png)
Additiponally, the screen moved a bit when the hand on screen moved. This can be mitigated by having a pieve of paper beneath the hand, or wearing some drawing gloves.

Was this what you meant? If not, could you clarify again?

**Comment by WorldTeacher** [comment]
How would I adjust the settings?

**Comment by NP-chaonay** [comment]
@WorldTeacher 

/etc/ipts.conf if I not remember wrong

**Comment by WorldTeacher** [comment]
So, I tried testing, but noticed something strange: the pen is not recognized anymore. It turns on, once i take it out of the cover, but it doesn't do anything on screen.  I tried setting the ipts.conf back to default, but it didn't work

**Comment by NP-chaonay** [comment]
> So, I tried testing, but noticed something strange: the pen is not recognized anymore. It turns on, once i take it out of the cover, but it doesn't do anything on screen. I tried setting the ipts.conf back to default, but it didn't work

does multitouch work?

**Comment by WorldTeacher** [comment]
Adding to last post: multitouch doesn't work anymore. I'll need to reinstall my os anyway, since i broke something in testing, so I'll give it another go tomorrow.

**Comment by WorldTeacher** [comment]
After a reinstallation and setting ithc and iptsd up, single touch and pen work. Didn't have the time to test multitouch yet, but I am assuming that it works.
