### ISSUE TITLE
Installation - No rule to make target 'dkms-install'

### ISSUE THREAD

**Issue by jeder49** [quo/ithc-linux#18]
when executing the command:
sudo make dkms-install

I allways get following error:
make: *** No rule to make target 'dkms-install'.  Stop.

I have installed "dkms" and "kernel-devel kernel-headers" (because I could not find and install "linux-headers-amd64").

**Comment by quo** [comment]
You need to `cd` to the `ithc-linux` directory first.

**Comment by jeder49** [comment]
Thanks!
