### ISSUE TITLE
Install errors due to module signing

### ISSUE THREAD

**Issue by ZoharKapach** [quo/ithc-linux#3]
I get these errors: when I run "make && sudo make install"

mkdir -p build
find build/ -type l -exec rm {} +
ln -sr src/* build/
make -C /lib/modules/`uname -r`/build M=/home/number6/ithc-linux/build
make[1]: Entering directory '/usr/src/linux-headers-5.15.0-30-generic'
make[1]: Leaving directory '/usr/src/linux-headers-5.15.0-30-generic'
make -C /lib/modules/`uname -r`/build M=/home/number6/ithc-linux/build modules_install
make[1]: Entering directory '/usr/src/linux-headers-5.15.0-30-generic'
arch/x86/Makefile:142: CONFIG_X86_X32 enabled but no binutils support
  INSTALL /lib/modules/5.15.0-30-generic/extra/ithc.ko
  SIGN    /lib/modules/5.15.0-30-generic/extra/ithc.ko
At main.c:160:
- SSL error:FFFFFFFF80000002:system library::No such file or directory: ../crypto/bio/bss_file.c:67
- SSL error:10000080:BIO routines::no such file: ../crypto/bio/bss_file.c:75
sign-file: certs/signing_key.pem: No such file or directory
  DEPMOD  /lib/modules/5.15.0-30-generic
Warning: modules_install: missing 'System.map' file. Skipping depmod.
make[1]: Leaving directory '/usr/src/linux-headers-5.15.0-30-generic'
depmod -a
sync

Do you know how I might be able to fix this?

**Comment by quo** [comment]
Looks like your kernel is configured to sign all modules, and it can't find a signing key ("sign-file: certs/signing_key.pem: No such file or directory").

You can (usually) check the relevant kernel config with: ``cat /boot/config-`uname -r`|grep MODULE_SIG``
Presumably this will show: `CONFIG_MODULE_SIG_FORCE=y` and `CONFIG_MODULE_SIG_ALL=y`.

In which case I think your options are:
1. Disable secure boot in your BIOS settings, and use an unsigned kernel instead.
2. Create your own signing key, enroll it into the UEFI key database, and tell kbuild to use it or sign the module manually.
3. Use DKMS which may handle all of this automatically depending on your distro.

Since the repository does not yet have a DKMS config file (I'll have to add that at some point), you'll have to configure DKMS manually for now, but it's probably the best option (if it works)...

**Comment by timonoj** [comment]
Thanks for this reply. I am having the same issue on my SP7+ (KDE Neon, which is an Ubuntu LTS). I believe the linux-surface kernel modules enable secure boot with mok, and I'm not sure it would be a good idea to disable it. And I don't have the faintest idea on how to enroll my own signing key onto the UEFI database and sign the module, nor configure DKMS manually...would you be able to provide some more details on how to go about this?
Sorry, and thanks!

**Comment by quo** [comment]
I've added DKMS config and instructions. Please let me know if it works!

> I believe the linux-surface kernel modules enable secure boot with mok, and I'm not sure it would be a good idea to disable it.

IMO secure boot is pointless unless you use full disk encryption, including encrypted /boot. And if you have full disk encryption, then module signing is kinda pointless. So I don't really understand why anyone would force enable module signing (but I'm sure they have their reasons).
It's probably a good idea to leave secure boot enabled though, unless you know what you're doing.

**Comment by timonoj** [comment]
Thanks so much! I just followed your simple instructions. I was asked to enroll the MOK key again (not exactly sure why), and after the reboot and enroll, my KDE Neon booted with a touchscreen!
I guess I'll have to figure now how to get a virtual keyboard working as well. Thanks! 

By the way, will you work towards adding this driver into the linux-surface package? That way it would be a rather seamless experience in the near future.

Again, thank you for your work!

**Comment by quo** [comment]
Great! Thanks.

> By the way, will you work towards adding this driver into the linux-surface package? That way it would be a rather seamless experience in the near future.

Sure, once it's been tested some more, and also on some different hardware (SP8), it can be added. But I'll leave that up to @qzed and @StollD.

And of course eventually it would be nice to get everything upstreamed, but I don't think I really have the patience to try that. :) So if anyone else wants to try, feel free.

**Comment by Pairman** [comment]
Same issue occured when I'm compiling for my SP7P.

Idk if this is related to https://github.com/quo/ithc-linux/issues/6#issuecomment-1146694465
