### ISSUE TITLE
Surface Laptop Studio support

### ISSUE THREAD

**Issue by quo** [quo/ithc-linux#8]
https://github.com/quo/ithc-linux/issues/5#issuecomment-1144003743
> Pen left click/hover work (doesnt test if detect as mouse or pen); MultiTouch dont work but logged in dmesg as msg "ithc 0000:00:10.6: truncated prd" when touch is done. (see below)

**Comment by NP-chaonay** [comment]
> [#5 (comment)](https://github.com/quo/ithc-linux/issues/5#issuecomment-1144003743)
> 
> > Pen left click/hover work (doesnt test if detect as mouse or pen); MultiTouch dont work but logged in dmesg as msg "ithc 0000:00:10.6: truncated prd" when touch is done. (see below)

UPDATED: That happen only on Wayland

for X11 in quo's version of IPTSD multi-touch mode
Except bug or something wrong on application-level
Basic multi-touch is work, Pen is work like before. No "ithc 0000:00:10.6: truncated prd" in dmesg output.

And single touch mode have same behaviour as Wayland (maybe all, if not then most)

Remark: Windows dragging is not work well On Gnome shell X11.

**Comment by NP-chaonay** [comment]
For more information before this issues has been created:
https://github.com/quo/ithc-linux/issues/5#issuecomment-1144003743

Futher information I might put here instead.

**Comment by NP-chaonay** [comment]
> (On surface kernel with IPTSD multitouch mode) logged in dmesg as msg "ithc 0000:00:10.6: truncated prd" when touch/pen is active/done.

I think it is useful to debug on generic kernel, because both version of kernel got different driver behaviour (see above and in my comment in #5)

**Comment by quo** [comment]
I'd like to get some more information about the 'truncated prd' error. Could you please try the following:
1. Apply the below patch. (This adds some extra logging to the ithc_dma_data_buffer_get function.)
2. Build and reinstall the driver: `make && sudo make install`
3. Reload the driver: `sudo modprobe -r ithc; sudo modprobe ithc`
4. Reproduce the 'truncated prd' error a few times.
5. Post the dmesg log.

Thanks!

```patch
diff --git a/src/ithc-dma.c b/src/ithc-dma.c
index b729893..f449dfc 100644
--- a/src/ithc-dma.c
+++ b/src/ithc-dma.c
@@ -97,6 +97,9 @@ static int ithc_dma_data_buffer_get(struct ithc *ithc, struct ithc_dma_prd_buffe
                b->data_size = 0;
                struct scatterlist *sg;
                int i;
+               for_each_sgtable_dma_sg(b->sgt, sg, i) {
+                       pci_info(ithc->pci, "buf %u, prd %i, dma size 0x%x, prd size 0x%x", idx, i, sg_dma_len(sg), prd[i].size);
+               }
                for_each_sgtable_dma_sg(b->sgt, sg, i) {
                        unsigned size = prd->size;
                        b->data_size += size & PRD_SIZE_MASK;
```

**Comment by NP-chaonay** [comment]
[ithc_dmesglog.zip](https://github.com/quo/ithc-linux/files/8839298/ithc_dmesglog.zip)
This is contains dmesg log when "trunccated prd" or touch/pen event occured; for these combination:
- Kernel: Generic/Surface
- Subsystem: X11/Wayland
- Input Event: Single touch (without IPTSD) / Multi-Touch / Pen

As I test, Doing multi-touch pressing / pen event on single touch mode doesnt give any message. (on every  combination of kernel/subsystem)
The difference between kernel is that multitouch works on generic but not on surface kernel.

**Comment by quo** [comment]
Thanks! Should be fixed now. Multitouch/pen should work with Surface kernel now.

(It was a slightly dumb bug. :) I had assumed the PRD_END_FLAG was the only flag in the PRD size field, but apparantly there are additional flags 0x2000000 (if PRD was filled succesfully) and 0x4000000 (if DMA was aborted due to CPU power state transition).)
